import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { Alert, Platform } from 'react-native';
import { Item } from '../types';

export async function exportToCSV(items: Item[]) {
    try {
        if (items.length === 0) {
            Alert.alert('Empty Pantry', 'No items to export.');
            return;
        }

        // CSV Header
        let csvContent = 'ID,Name,Quantity,Unit,Location,Expiry,Status\n';

        // CSV Rows
        items.forEach(item => {
            const expiry = item.expires ? new Date(item.expires).toLocaleDateString() : '';
            const status = item.consumedAt ? 'Consumed' : (item.onShoppingList ? 'Shopping List' : 'In Pantry');
            const row = [
                item.id,
                `"${item.name.replace(/"/g, '""')}"`, // Escape quotes
                item.quantity || 0,
                item.unit || '',
                `"${(item.location || '').replace(/"/g, '""')}"`,
                expiry,
                status
            ].join(',');
            csvContent += row + '\n';
        });

        const fileName = `pantry_export_${Date.now()}.csv`;
        // @ts-ignore
        const docDir = FileSystem.documentDirectory;
        const filePath = `${docDir}${fileName}`;

        await (FileSystem as any).writeAsStringAsync(filePath, csvContent, { encoding: 'utf8' });

        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync(filePath);
        } else {
            Alert.alert('Sharing not available', 'Cannot share files on this device configuration.');
        }
    } catch (error: any) {
        console.error('Export CSV Error:', error);
        Alert.alert('Export Failed', error.message);
    }
}

export async function exportToPDF(items: Item[], userDisplayName?: string | null) {
    try {
        if (items.length === 0) {
            Alert.alert('Empty Pantry', 'No items to export.');
            return;
        }

        const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; }
            h1 { color: #5b6cff; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #f3f4f6; padding: 10px; text-align: left; border-bottom: 2px solid #ddd; }
            td { padding: 10px; border-bottom: 1px solid #eee; }
            .expired { color: #ef4444; font-weight: bold; }
            .footer { margin-top: 40px; color: #888; font-size: 12px; text-align: center; }
          </style>
        </head>
        <body>
          <h1>Pantry Inventory Report</h1>
          <p>Generated for: <strong>${userDisplayName || 'User'}</strong> on ${new Date().toLocaleDateString()}</p>
          
          <table>
            <thead>
              <tr>
                <th>Item</th>
                <th>Qty</th>
                <th>Location</th>
                <th>Expiry</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${items.map(item => {
            const isExpired = item.expires && new Date(item.expires).getTime() < Date.now();
            const expiryText = item.expires ? new Date(item.expires).toLocaleDateString() : '—';
            return `
                  <tr>
                    <td><strong>${item.name}</strong></td>
                    <td>${item.quantity || 1} ${item.unit || ''}</td>
                    <td>${item.location || 'Pantry'}</td>
                    <td class="${isExpired ? 'expired' : ''}">${expiryText}</td>
                    <td>${item.consumedAt ? 'Consumed' : (item.onShoppingList ? 'Shop List' : 'Stocked')}</td>
                  </tr>
                `;
        }).join('')}
            </tbody>
          </table>

          <div class="footer">
            Generated by Pantry Organizer App
          </div>
        </body>
      </html>
    `;

        const { uri } = await Print.printToFileAsync({ html: htmlContent });

        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
        } else {
            Alert.alert('Saved', `PDF saved to: ${uri}`);
        }
    } catch (error: any) {
        console.error('Export PDF Error:', error);
        Alert.alert('Export Failed', error.message);
    }
}
